---
# tasks file for webserver
  - name: Install Required Package
    package:
            name: python3
            state: present
    become: true

  - name: install httpd package
    package:
            name: "httpd"
            state: present
    when: ansible_distribution == "RedHat"
    become: true
    register: x

  - name: document root dir
    file:
            state: directory
            dest:  "{{ dcdir }}"
    register: y
    become: true

  - name: Webserver Started
    service:
            name: "httpd"
            state: started
    become: true

  - name: conf web server
    template:
            dest: /etc/httpd/conf.d/gaurav.conf
            src: templates/localconf.conf.j2
    when: x.rc == 0
    notify: restart services
    become: true

  - name: copy web page from url
    copy:
            content: "{{ ansible_default_ipv4.address }}"
            dest: "{{ dcdir }}/index.html"           
    when: y.failed ==  false
    become: true
